# Generated by Django 4.0.4 on 2022-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='')),
                ('sevice_1', models.BooleanField(default=False)),
                ('sevice_2', models.BooleanField(default=False)),
                ('sevice_3', models.BooleanField(default=False)),
                ('sevice_4', models.BooleanField(default=False)),
                ('sevice_5', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('period', models.ImageField(upload_to='')),
            ],
        ),
    ]
