# Generated by Django 4.0.4 on 2022-04-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_info',
        ),
    ]
