# Generated by Django 4.0.3 on 2022-04-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_info',
        ),
    ]
