# Generated by Django 4.0.3 on 2022-04-22 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_service_info_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_info',
        ),
    ]
