# Generated by Django 4.0.3 on 2022-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_delete_service_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='servs_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('servname', models.CharField(max_length=20)),
            ],
        ),
    ]
