# Generated by Django 4.0.3 on 2022-04-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_servs_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='id16200422',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('cabinet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lt_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField()),
                ('service', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medical_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_img', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=50)),
                ('birth_dmy', models.DateField()),
                ('birth_plc', models.CharField(max_length=50)),
                ('cong_dis', models.CharField(max_length=100)),
                ('blood_tp', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='prof_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile_information',
        ),
        migrations.DeleteModel(
            name='servs_information',
        ),
    ]
