# Generated by Django 4.0.3 on 2022-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_id16200422_lt_service_medical_card_prof_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('service', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('cabinet', models.IntegerField()),
            ],
        ),
    ]
